name = "nextjs-13-app-playground-migration-gateway-worker"
main = "src/worker.ts"
compatibility_date = "2023-06-15"

[vars]
NODE_APP_BASE_URL = "https://next-js-13-app-playground-sigma.vercel.app"
NEXT_ON_PAGES_BASE_URL = "https://next-js-13-app-playground-migration-poc.pages.dev"
